# Example paths configuration
# Copy this to configs/paths.local.yml and fill in your actual paths
# Do NOT commit paths.local.yml — it will be added to .gitignore

machine: jasmin

roots:
  scratch: /work/scratch-nopw2/cornkle
  network_data: /gws/ssde/j25b/
  lmcs: /gws/ssde/j25b/lmcs
  other: /gws/ssde/j25b/cocoon

datasets:
  cp4_root: "/gws/ssde/j25b/impala/shared/CP4A/ncfiles"
  cp4_tables: "{lmcs}/cklein/CP_models/MCS_files/WAf/moved_fromCEH/tables/"
  cp4_2d: "{lmcs}/cklein/CP_models/MCS_files/WAf/"
  mcs_5000km2_tables_v2: "{other}/MCS_5000km2_tables_v2/ERA5_storm_timeseries"


figures:
  lmcs_figs: "/gws/ssde/j25b/cocoon/figs/LMCS/"
